name: RSpec

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile: [ rails-5.2, rails-6.0, rails-6.1 ]
        ruby: [ '2.7' ]
        include:
          - gemfile: rails-6.1
            ruby: '3.0'
          - gemfile: rails-7.0
            ruby: '2.7'
          - gemfile: rails-7.0
            ruby: '3.0'
          - gemfile: rails-7.0-propshaft
            ruby: '3.0'
          - gemfile: rails-7.1
            ruby: '3.3'
          - gemfile: rails-7.1-propshaft
            ruby: '3.3'
          - gemfile: rails-7.2
            ruby: '3.3'
          - gemfile: rails-7.2-propshaft
            ruby: '3.3'
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run Specs
      run: bundle exec rake

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v2
      with:
        flag-name: run-${{ join(matrix.*, '-') }}
        parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
